// <auto-generated />
using System;
using FMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FMS.Migrations
{
    [DbContext(typeof(FMSDbContext))]
    [Migration("20260101150957_TenMigrationCuaBan")]
    partial class TenMigrationCuaBan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExtraExpense", b =>
                {
                    b.Property<int>("ExtraExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraExpenseID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("ExtraExpenseID");

                    b.HasIndex("TripID");

                    b.ToTable("ExtraExpenses");
                });

            modelBuilder.Entity("FMS.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<string>("DriverStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("int");

                    b.HasKey("DriverID");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("FMS.Models.DriverLicense", b =>
                {
                    b.Property<int>("DriverLicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverLicenseID"));

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LicenseClassID")
                        .HasColumnType("int");

                    b.HasKey("DriverLicenseID");

                    b.HasIndex("LicenseClassID");

                    b.HasIndex("DriverID", "LicenseClassID")
                        .IsUnique();

                    b.ToTable("DriverLicenses");
                });

            modelBuilder.Entity("FMS.Models.EmergencyReport", b =>
                {
                    b.Property<int>("EmergencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmergencyID"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RespondedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TripID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("EmergencyID");

                    b.HasIndex("DriverID");

                    b.HasIndex("TripID");

                    b.HasIndex("VehicleID");

                    b.ToTable("EmergencyReports");
                });

            modelBuilder.Entity("FMS.Models.FuelRecord", b =>
                {
                    b.Property<int>("FuelRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuelRecordID"));

                    b.Property<double>("CurrentKm")
                        .HasColumnType("float");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<double>("FuelAmount")
                        .HasColumnType("float");

                    b.Property<double>("FuelCost")
                        .HasColumnType("float");

                    b.Property<DateTime>("FuelTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReFuelLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TripID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("FuelRecordID");

                    b.HasIndex("DriverID");

                    b.HasIndex("FuelTime");

                    b.HasIndex("TripID");

                    b.HasIndex("VehicleID");

                    b.ToTable("FuelRecords");
                });

            modelBuilder.Entity("FMS.Models.LicenseClass", b =>
                {
                    b.Property<int>("LicenseClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseClassID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LicenseDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LicenseClassID");

                    b.ToTable("LicenseClasses");
                });

            modelBuilder.Entity("FMS.Models.Maintenance", b =>
                {
                    b.Property<int>("MaintenanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceID"));

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GarageName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaintenanceStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TechnicianName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceID");

                    b.HasIndex("VehicleID");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("FMS.Models.MaintenanceService", b =>
                {
                    b.Property<int>("MaintenanceServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceServiceID"));

                    b.Property<int>("MaintenanceID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("MaintenanceServiceID");

                    b.HasIndex("MaintenanceID");

                    b.HasIndex("ServiceID");

                    b.ToTable("MaintenanceServices");
                });

            modelBuilder.Entity("FMS.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("ServicePrice")
                        .HasColumnType("float");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("FMS.Models.Trip", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripID"));

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalDistanceKm")
                        .HasColumnType("int");

                    b.Property<double?>("TotalFuelConsumed")
                        .HasColumnType("float");

                    b.Property<string>("TripStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleID1")
                        .HasColumnType("int");

                    b.HasKey("TripID");

                    b.HasIndex("StartTime");

                    b.HasIndex("VehicleID");

                    b.HasIndex("VehicleID1");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("FMS.Models.TripStep", b =>
                {
                    b.Property<int>("TripStepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripStepID"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StepLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("TripStepID");

                    b.HasIndex("TripID", "StepKey")
                        .IsUnique();

                    b.ToTable("TripSteps");
                });

            modelBuilder.Entity("FMS.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsReceivingEmailNofication")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReceivingGeoNofication")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReceivingMaintainNofication")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReceivingReportNofication")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FMS.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleID"));

                    b.Property<int?>("CurrentKm")
                        .HasColumnType("int");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManufacturedYear")
                        .HasColumnType("int");

                    b.Property<int>("RequiredLicenseClassID")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleID");

                    b.HasIndex("DriverID");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("RequiredLicenseClassID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FMS.Models.VehicleDriverAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<DateTime>("AssignedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AssignedTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<int>("VehicleID")
                        .HasColumnType("int");

                    b.HasKey("AssignmentID");

                    b.HasIndex("DriverID");

                    b.HasIndex("VehicleID");

                    b.ToTable("VehicleDriverAssignments");
                });

            modelBuilder.Entity("TripDriver", b =>
                {
                    b.Property<int>("TripDriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripDriverID"));

                    b.Property<DateTime>("AssignedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AssignedTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.Property<double?>("TripRating")
                        .HasColumnType("float");

                    b.HasKey("TripDriverID");

                    b.HasIndex("DriverID");

                    b.HasIndex("TripID", "DriverID")
                        .IsUnique();

                    b.ToTable("TripDrivers");
                });

            modelBuilder.Entity("TripLog", b =>
                {
                    b.Property<int>("TripLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripLogID"));

                    b.Property<int>("DistanceFromLastKm")
                        .HasColumnType("int");

                    b.Property<double>("FuelUsed")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("TripLogID");

                    b.HasIndex("TripID", "LogTime");

                    b.ToTable("TripLogs");
                });

            modelBuilder.Entity("ExtraExpense", b =>
                {
                    b.HasOne("FMS.Models.Trip", "Trip")
                        .WithMany("ExtraExpenses")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FMS.Models.DriverLicense", b =>
                {
                    b.HasOne("FMS.Models.Driver", "Driver")
                        .WithMany("DriverLicenses")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMS.Models.LicenseClass", "LicenseClass")
                        .WithMany()
                        .HasForeignKey("LicenseClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("LicenseClass");
                });

            modelBuilder.Entity("FMS.Models.EmergencyReport", b =>
                {
                    b.HasOne("FMS.Models.Driver", "Driver")
                        .WithMany("EmergencyReports")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FMS.Models.Trip", "Trip")
                        .WithMany("EmergencyReports")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FMS.Models.Vehicle", "Vehicle")
                        .WithMany("EmergencyReports")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FMS.Models.FuelRecord", b =>
                {
                    b.HasOne("FMS.Models.Driver", "Driver")
                        .WithMany("FuelRecords")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMS.Models.Trip", "Trip")
                        .WithMany("FuelRecords")
                        .HasForeignKey("TripID");

                    b.HasOne("FMS.Models.Vehicle", "Vehicle")
                        .WithMany("FuelRecords")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FMS.Models.Maintenance", b =>
                {
                    b.HasOne("FMS.Models.Vehicle", "Vehicle")
                        .WithMany("Maintenances")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FMS.Models.MaintenanceService", b =>
                {
                    b.HasOne("FMS.Models.Maintenance", "Maintenance")
                        .WithMany("MaintenanceServices")
                        .HasForeignKey("MaintenanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMS.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maintenance");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FMS.Models.Trip", b =>
                {
                    b.HasOne("FMS.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMS.Models.Vehicle", null)
                        .WithMany("Trips")
                        .HasForeignKey("VehicleID1");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FMS.Models.TripStep", b =>
                {
                    b.HasOne("FMS.Models.Trip", "Trip")
                        .WithMany("TripSteps")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FMS.Models.Vehicle", b =>
                {
                    b.HasOne("FMS.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID");

                    b.HasOne("FMS.Models.LicenseClass", "RequiredLicenseClass")
                        .WithMany()
                        .HasForeignKey("RequiredLicenseClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("RequiredLicenseClass");
                });

            modelBuilder.Entity("FMS.Models.VehicleDriverAssignment", b =>
                {
                    b.HasOne("FMS.Models.Driver", "Driver")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMS.Models.Vehicle", "Vehicle")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TripDriver", b =>
                {
                    b.HasOne("FMS.Models.Driver", "Driver")
                        .WithMany("TripDrivers")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMS.Models.Trip", "Trip")
                        .WithMany("TripDrivers")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripLog", b =>
                {
                    b.HasOne("FMS.Models.Trip", "Trip")
                        .WithMany("TripLogs")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("FMS.Models.Driver", b =>
                {
                    b.Navigation("DriverLicenses");

                    b.Navigation("EmergencyReports");

                    b.Navigation("FuelRecords");

                    b.Navigation("TripDrivers");

                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("FMS.Models.Maintenance", b =>
                {
                    b.Navigation("MaintenanceServices");
                });

            modelBuilder.Entity("FMS.Models.Trip", b =>
                {
                    b.Navigation("EmergencyReports");

                    b.Navigation("ExtraExpenses");

                    b.Navigation("FuelRecords");

                    b.Navigation("TripDrivers");

                    b.Navigation("TripLogs");

                    b.Navigation("TripSteps");
                });

            modelBuilder.Entity("FMS.Models.Vehicle", b =>
                {
                    b.Navigation("EmergencyReports");

                    b.Navigation("FuelRecords");

                    b.Navigation("Maintenances");

                    b.Navigation("Trips");

                    b.Navigation("VehicleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
